### ISSUE TITLE
No support for yolov5v6

### ISSUE THREAD

**Issue by NaveedAI** [BlueMirrors/cvu#27]
Hi,
I got the following error when I try to convert the yolov5v6.onnx 
```
[CVU-Info] Backend: Tensorrt-8.0.1.6-cuda
[CVU-Info] Building and Optimizing TRT-Engine for input_shape=(384, 640). This might take a few minutes for first time.
[TensorRT] INFO: [MemUsageChange] Init CUDA: CPU +0, GPU +0, now: CPU 0, GPU 353 (MiB)
[CVU-Info] Platform has fp16 support. Setting fp16 to True
[TensorRT] WARNING: onnx2trt_utils.cpp:364: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
In node 279 (importRange): UNSUPPORTED_NODE: Assertion failed: inputs.at(0).isInt32() && "For range operator with dynamic inputs, this version of TensorRT only supports INT32!"
[TensorRT] ERROR: 4: [network.cpp::validate::2411] Error Code 4: Internal Error (Network must have at least one output)
Traceback (most recent call last):
  File "detect.py", line 126, in <module>
    not opt.no_auto_install)
  File "detect.py", line 74, in detect_image
    preds = model(image)
  File "/usr/local/lib/python3.7/dist-packages/cvu/detector/yolov5/core.py", line 102, in __call__
    outputs = self._model(processed_inputs)
  File "/usr/local/lib/python3.7/dist-packages/cvu/detector/yolov5/backends/yolov5_tensorrt.py", line 307, in __call__
    self._load_model(self._weight)
  File "/usr/local/lib/python3.7/dist-packages/cvu/detector/yolov5/backends/yolov5_tensorrt.py", line 142, in _load_model
    self._input_shape)
  File "/usr/local/lib/python3.7/dist-packages/cvu/detector/yolov5/backends/yolov5_tensorrt.py", line 262, in _build_engine
    trt_engine_file.write(engine.serialize())
AttributeError: 'NoneType' object has no attribute 'serialize'
```

Any instructions how to convert?

**Comment by aditya-dl** [comment]
Hello @NaveedAI, we have identified the issue and are working on a solution.

**Comment by thegrogu** [comment]
@NaveedAI I think your onnx model is with dynamic shapes? 
You need to export onnx model without the ```--dynamic``` flag from ultralytics/yolov5 and this would work just fine. The problem you mentioned is a known issue with latest tensorrt and onnx versions. 
- So, export your onnx model with yolov5 ```python export.py --imgsz "height" "width"``` (without the dynamic flag).
- And use the generated onnx model to create the tensorrt engine.
- 
These are my logs for reference.:
```
static/yolov5s6.onnx
(384, 640, 3)
(384, 640, 3)
[CVU-Info] Building and Optimizing TRT-Engine for input_shape=(384, 640). This might take a few minutes for first time.
[06/11/2022-10:41:34] [TRT] [I] [MemUsageChange] Init CUDA: CPU +313, GPU +0, now: CPU 362, GPU 244 (MiB)
[06/11/2022-10:41:34] [TRT] [I] [MemUsageSnapshot] Begin constructing builder kernel library: CPU 362 MiB, GPU 244 MiB
[06/11/2022-10:41:34] [TRT] [I] [MemUsageSnapshot] End constructing builder kernel library: CPU 497 MiB, GPU 278 MiB
[CVU-Info] Platform has fp16 support. Setting fp16 to True
[06/11/2022-10:41:34] [TRT] [W] parsers/onnx/onnx2trt_utils.cpp:364: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[06/11/2022-10:41:35] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +518, GPU +224, now: CPU 1071, GPU 502 (MiB)
[06/11/2022-10:41:35] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +115, GPU +54, now: CPU 1186, GPU 556 (MiB)
[06/11/2022-10:41:35] [TRT] [I] Local timing cache in use. Profiling results in this builder pass will not be stored.
[06/11/2022-10:42:40] [TRT] [I] Some tactics do not have sufficient workspace memory to run. Increasing workspace size may increase performance, please check verbose output.
[06/11/2022-10:50:18] [TRT] [I] Detected 1 inputs and 5 output network tensors.
[06/11/2022-10:50:18] [TRT] [I] Total Host Persistent Memory: 169040
[06/11/2022-10:50:18] [TRT] [I] Total Device Persistent Memory: 23151104
[06/11/2022-10:50:18] [TRT] [I] Total Scratch Memory: 0
[06/11/2022-10:50:18] [TRT] [I] [MemUsageStats] Peak memory usage of TRT CPU/GPU memory allocators: CPU 31 MiB, GPU 225 MiB
[06/11/2022-10:50:18] [TRT] [I] [BlockAssignment] Algorithm ShiftNTopDown took 33.7113ms to assign 11 blocks to 139 nodes requiring 18726403 bytes.
[06/11/2022-10:50:18] [TRT] [I] Total Activation Memory: 18726403
[06/11/2022-10:50:18] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 1761, GPU 816 (MiB)
[06/11/2022-10:50:18] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +1, GPU +8, now: CPU 1762, GPU 824 (MiB)
[06/11/2022-10:50:18] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in building engine: CPU +24, GPU +32, now: CPU 24, GPU 32 (MiB)
[CVU-Info] Engine serialized and saved !
[06/11/2022-10:50:18] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +10, now: CPU 1749, GPU 800 (MiB)
[06/11/2022-10:50:18] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 1749, GPU 808 (MiB)
[06/11/2022-10:50:18] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +39, now: CPU 24, GPU 71 (MiB)


Total Time Taken:  525.28 seconds.
Engine File Saved at:  static/yolov5s6.engine
```

And these are the outputs after inference:

```
root@a20af9be6c00:/home# python examples/example_video_simple.py -v static/zidane.jpg 
[CVU-Info] Building and Optimizing TRT-Engine for input_shape=(384, 640). This might take a few minutes for first time.
[06/11/2022-12:07:36] [TRT] [I] [MemUsageChange] Init CUDA: CPU +313, GPU +0, now: CPU 353, GPU 244 (MiB)
[06/11/2022-12:07:36] [TRT] [I] Loaded engine size: 28 MiB
[06/11/2022-12:07:36] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +519, GPU +224, now: CPU 911, GPU 498 (MiB)
[06/11/2022-12:07:37] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +114, GPU +52, now: CPU 1025, GPU 550 (MiB)
[06/11/2022-12:07:37] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +26, now: CPU 0, GPU 26 (MiB)
[06/11/2022-12:07:37] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +10, now: CPU 996, GPU 542 (MiB)
[06/11/2022-12:07:37] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 996, GPU 550 (MiB)
[06/11/2022-12:07:37] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +23, now: CPU 0, GPU 49 (MiB)
id:0    class=Person;   conf=0.9;       top-left=(135.0, 195.0);        bottom-right=(1126.0, 719.0)
id:1    class=Person;   conf=0.83;      top-left=(748.0, 39.0 );        bottom-right=(1154.0, 711.0)
id:2    class=Tie;      conf=0.42;      top-left=(440.0, 437.0);        bottom-right=(508.0, 712.0)
```

Closing this for now. Feel free to re-open if the suggestion does not resolve your issue
