### ISSUE TITLE
tensorrt ValuError while onnx is working

### ISSUE THREAD

**Issue by ronin2304** [BlueMirrors/cvu#46]
_Hi , I am trying to run infernce on a yolov5 model using tensorrt backend. It works fine with onnx backend in "auto" mode using gpu and in "cpu" as well . when I use the tensorrt backend I get the error message:cannot reshape array of size 280500 into shape (1,newaxis,8). 
the full trace is:_
 [CVU-Info] Building and Optimizing TRT-Engine for input_shape=(640, 640). This might take a few minutes for first time.
[03/27/2023-11:41:21] [TRT] [I] Loaded engine size: 270 MiB
[03/27/2023-11:41:21] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +268, now: CPU 0, GPU 268 (MiB)
[03/27/2023-11:41:21] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +43, now: CPU 0, GPU 311 (MiB)
[03/27/2023-11:41:21] [TRT] [E] 1: [pointWiseV2Helpers.cpp::launchPwgenKernel::282] Error Code 1: Cuda Driver (invalid resource handle)
Traceback (most recent call last):
  File "/run/user/1000/gvfs/smb-share:server=ednas.local,share=promethai/transfer/parsec_checkpoints/onnx_test_no_jupyter.py", line 28, in <module>
    preds = infer(image,detector)
  File "/run/user/1000/gvfs/smb-share:server=ednas.local,share=promethai/transfer/parsec_checkpoints/onnx_test_no_jupyter.py", line 19, in infer
    preds = detector(image)
  File "/home/ed/anaconda3/envs/prometai_v1/lib/python3.8/site-packages/cvu/detector/yolov5/core.py", line 106, in __call__
    outputs = self._model(processed_inputs)
  File "/home/ed/anaconda3/envs/prometai_v1/lib/python3.8/site-packages/cvu/detector/yolov5/backends/yolov5_tensorrt.py", line 320, in __call__
    preds = self._post_process(outputs)
  File "/home/ed/anaconda3/envs/prometai_v1/lib/python3.8/site-packages/cvu/detector/yolov5/backends/yolov5_tensorrt.py", line 369, in _post_process
    outputs = outputs[-1].reshape((1, -1, self._nc + 5))
ValueError: cannot reshape array of size 280500 into shape (1,newaxis,8) #

_I initially had an error that stated :_

 [CVU-Info] Building and Optimizing TRT-Engine for input_shape=(640, 640). This might take a few minutes for first time.
[03/27/2023-11:10:37] [TRT] [I] [MemUsageChange] Init CUDA: CPU +318, GPU +0, now: CPU 383, GPU 1440 (MiB)
[03/27/2023-11:10:39] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +442, GPU +116, now: CPU 880, GPU 1545 (MiB)
[03/27/2023-11:10:39] [TRT] [W] CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage. See `CUDA_MODULE_LOADING` in https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars
[CVU-Info] Platform has fp16 support. Setting fp16 to True
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:604] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:81] The total number of bytes read was 560598739
[03/27/2023-11:10:39] [TRT] [W] onnx2trt_utils.cpp:377: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[03/27/2023-11:10:41] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +854, GPU +362, now: CPU 2311, GPU 1905 (MiB)
[03/27/2023-11:10:41] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +129, GPU +58, now: CPU 2440, GPU 1963 (MiB)
[03/27/2023-11:10:41] [TRT] [W] TensorRT was linked against cuDNN 8.6.0 but loaded cuDNN 8.5.0
[03/27/2023-11:10:41] [TRT] [I] Local timing cache in use. Profiling results in this builder pass will not be stored.
[03/27/2023-11:12:05] [TRT] [I] Some tactics do not have sufficient workspace memory to run. Increasing workspace size will enable more tactics, please check verbose output for requested sizes.

    

[03/27/2023-11:17:55] [TRT] [I] Total Activation Memory: 377833472
[03/27/2023-11:17:55] [TRT] [I] Detected 1 inputs and 5 output network tensors.
[03/27/2023-11:17:58] [TRT] [I] Total Host Persistent Memory: 524032
[03/27/2023-11:17:58] [TRT] [I] Total Device Persistent Memory: 1577984
[03/27/2023-11:17:58] [TRT] [I] Total Scratch Memory: 0
[03/27/2023-11:17:58] [TRT] [I] [MemUsageStats] Peak memory usage of TRT CPU/GPU memory allocators: CPU 309 MiB, GPU 268 MiB
[03/27/2023-11:17:58] [TRT] [I] [BlockAssignment] Started assigning block shifts. This will take 243 steps to complete.
[03/27/2023-11:17:58] [TRT] [I] [BlockAssignment] Algorithm ShiftNTopDown took 21.2057ms to assign 10 blocks to 243 nodes requiring 42944512 bytes.
[03/27/2023-11:17:58] [TRT] [I] Total Activation Memory: 42944512
[03/27/2023-11:17:58] [TRT] [W] TensorRT encountered issues when converting weights between types and that could affect accuracy.
[03/27/2023-11:17:58] [TRT] [W] If this is not the desired behavior, please modify the weights or retrain with regularization to adjust the magnitude of the weights.
[03/27/2023-11:17:58] [TRT] [W] Check verbose logs for the list of affected weights.
[03/27/2023-11:17:58] [TRT] [W] - 160 weights are affected by this issue: Detected subnormal FP16 values.
[03/27/2023-11:17:58] [TRT] [W] - 3 weights are affected by this issue: Detected values less than smallest positive FP16 subnormal value and converted them to the FP16 minimum subnormalized value.
[03/27/2023-11:17:58] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in building engine: CPU +267, GPU +269, now: CPU 267, GPU 269 (MiB)
[CVU-Info] Engine serialized and saved !
[03/27/2023-11:17:58] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +42, now: CPU 267, GPU 311 (MiB)
[03/27/2023-11:17:58] [TRT] [W] CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage. See `CUDA_MODULE_LOADING` in https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars
/home/ed/anaconda3/envs/prometai_v1/lib/python3.8/site-packages/tensorrt/__init__.py:166: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.  (This may have returned Python scalars in past versions.
  bool: np.bool,
Traceback (most recent call last):
  File "/run/user/1000/gvfs/smb-share:server=ednas.local,share=promethai/transfer/parsec_checkpoints/onnx_test_no_jupyter.py", line 25, in <module>
    preds = infer(image,detector)
  File "/run/user/1000/gvfs/smb-share:server=ednas.local,share=promethai/transfer/parsec_checkpoints/onnx_test_no_jupyter.py", line 17, in infer
    preds = detector(image)
  File "/home/ed/anaconda3/envs/prometai_v1/lib/python3.8/site-packages/cvu/detector/yolov5/core.py", line 106, in __call__
    outputs = self._model(processed_inputs)
  File "/home/ed/anaconda3/envs/prometai_v1/lib/python3.8/site-packages/cvu/detector/yolov5/backends/yolov5_tensorrt.py", line 308, in __call__
    self._allocate_buffers()
  File "/home/ed/anaconda3/envs/prometai_v1/lib/python3.8/site-packages/cvu/detector/yolov5/backends/yolov5_tensorrt.py", line 272, in _allocate_buffers
    dtype = trt.nptype(self._engine.get_binding_dtype(binding))
  File "/home/ed/anaconda3/envs/prometai_v1/lib/python3.8/site-packages/tensorrt/__init__.py", line 166, in nptype
    bool: np.bool,
  File "/home/ed/anaconda3/envs/prometai_v1/lib/python3.8/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'bool'
[03/27/2023-11:17:59] [TRT] [E] 1: [resizingAllocator.cpp::deallocate::105] Error Code 1: Cuda Runtime (invalid argument)
[03/27/2023-11:17:59] [TRT] [E] 1: [resizingAllocator.cpp::deallocate::105] Error Code 1: Cuda Runtime (invalid argument)
[03/27/2023-11:17:59] [TRT] [E] 1: [resizingAllocator.cpp::deallocate::105] Error Code 1: Cuda Runtime (invalid argument) # 

_which i found to be a numpy version issue since types in 1.24.1 are deprecated ( as info), I downgraded numpy tp 1.23.1 and received above first error . 
Does anyone have an idea wht can be done to mitigate? 
Thanks_

**Comment by Hyrtsi** [comment]
@ronin2304 can you share a minimal working example code to reproduce the error?

What kind of data are you using for the model? What is your batch size?

This error

```
 ValueError: cannot reshape array of size 280500 into shape (1,newaxis,8) #
 ```
 
 makes sense: `280500` is not divisible by `8`. Maybe you should investigate what this value is. Maybe the pixels in your image, hard to say before you post the code. Thank you.

**Comment by mavihs7** [comment]
closing for inactivity.
