### ISSUE TITLE
Images with different resolution throw error

### ISSUE THREAD

**Issue by ronin2304** [BlueMirrors/cvu#47]
Hi again , I now tried images with different resolution other than than 640 x640 and the inference fails on a custom onnx model. I did as mentioned in https://github.com/BlueMirrors/cvu/issues/27#issuecomment-1152957355. But the letterbox preprocessing will not resize , of course I could adapt but that would change the original image so the output would have the letterbox , too, I believe, which would throw of the coordinate values that I need . This issue does not exist with your "standard" yolo model for coco.
the error upon running inference is:
['CPUExecutionProvider']
Traceback (most recent call last):
  File "/run/user/1000/gvfs/smb-share:server=ednas.local,share=promethai/transfer/parsec_checkpoints/onnx_test_no_jupyter.py", line 31, in <module>
    preds = infer(image,detector)
  File "/run/user/1000/gvfs/smb-share:server=ednas.local,share=promethai/transfer/parsec_checkpoints/onnx_test_no_jupyter.py", line 20, in infer
    preds = detector(image)
  File "/home/ed/anaconda3/envs/prometai_v1/lib/python3.8/site-packages/cvu/detector/yolov5/core.py", line 106, in __call__
    outputs = self._model(processed_inputs)
  File "/home/ed/anaconda3/envs/prometai_v1/lib/python3.8/site-packages/cvu/detector/yolov5/backends/yolov5_onnx.py", line 126, in __call__
    outputs = self._model.run([self._model.get_outputs()[0].name],
  File "/home/ed/anaconda3/envs/prometai_v1/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: images for the following indices
 index: 2 Got: 416 Expected: 640

for an image with dim(413,640)
Has anyone had success with a custom model inference with dynamic image input resolution? 
**Edit:**
It seems that in the letterbox function auto uses the default "True" somehow, althoug when called from core.py
self._preprocess = [lambda image: letterbox(image, kwargs['input_shape'], auto=False), should pass "False"  from what I see at the moment.
**Edit:**
And another one: for those who may have the same issue and subsequent revelation, when instantiation the detector class add, the parameter "input_shape"  and your tuple of img dimensions as per your model. that does the trick...

**Comment by ronin2304** [comment]
****This can be closed
